name: ELECTRON
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: orhun/git-cliff-action@v4
        with:
          args: --latest --config github --include-unconventional
        env:
          OUTPUT: release-notes.md
      - uses: actions/upload-artifact@v7
        with:
          name: release-notes
          path: release-notes.md
          retention-days: 1
  build:
    needs: changelog
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v7
        with:
          name: release-notes
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: "npm"
      - run: npm ci
      - if: matrix.os == 'ubuntu-latest'
        run: sudo snap install snapcraft --classic
      - run: npm run build:electron
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
